#story=  another normal day, your parents punished you, you will be locked down in your house after you failed an asigment , you ended up your clases   
# school can take a lot of your energy so you just decide to take a nap
#  when you wake up you realize something in your room started a fire, find the way to scape 

import random


print("welcome to this game")

player_name=input("write your character's name\n")
print(player_name+ ", I hope you can scape!!")
